inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
