sudo: required

# Don't bother installing ruby outside of docker. The C language is hopefully
# a fairly minimal thing to load.
language: C

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker build -t compare_compressors .

script: docker run --rm -it --entrypoint='' compare_compressors bundle exec rake
