sudo: required

services:
  - docker

before_install:
  - docker build -t jdleesmiller/compare_compressors .

script:
  - docker run --rm -it --entrypoint='' jdleesmiller/compare_compressors bundle exec rake
